### ISSUE TITLE
Is the pull-stream approach generalized across languages?

### ISSUE THREAD

**Issue by anderspitman** [libp2p/interface-stream-muxer#52]
I noticed you're using pull-streams, which is awesome. I'm curious if you've found a good method of generalizing the approach to work in Go/Rust?

**Comment by jacobheun** [comment]
No, currently the pull-stream usage is limited to the js side of things. I don't believe we have any plans at the moment to generalize that.

While the interface was originally designed to test implementations in each of the languages, it's currently only being used for the js muxer implementations.

**Comment by Stebalien** [comment]
Streams are *always* "pull" in go and rust.

**Comment by anderspitman** [comment]
@Stebalien that's interesting. Is that because in Go for example you usually consume readers in a go routine and block on read if no data is available?
