### ISSUE TITLE
Are muxers supposed/required to export their multicodec?

### ISSUE THREAD

**Issue by emschwartz** [libp2p/interface-stream-muxer#6]
[`js-libp2p-spdy`](https://github.com/libp2p/js-libp2p-spdy/blob/master/src/index.js#L64) and [`js-libp2p-multiplex`](https://github.com/libp2p/js-libp2p-multiplex/blob/master/src/index.js#L30) do and that seems like a fairly useful feature for the interface.

**Comment by diasdavid** [comment]
Not required per se, but we do it because it keeps things organised :)
